export const MarketABI = [
	{
		type: 'constructor',
		inputs: [
			{ name: '_question', type: 'string' },
			{ name: '_outcomeCount', type: 'uint256' },
			{ name: '_deadline', type: 'uint256' },
			{ name: '_gracePeriod', type: 'uint256' },
			{ name: '_signer', type: 'address' },
			{ name: '_feeRecipient', type: 'address' },
			{ name: '_feeBps', type: 'uint256' },
		],
		stateMutability: 'nonpayable',
	},
	{
		type: 'function',
		name: 'bet',
		inputs: [{ name: 'outcomeIndex', type: 'uint256' }],
		outputs: [],
		stateMutability: 'payable',
	},
	{
		type: 'function',
		name: 'cancel',
		inputs: [{ name: 'signature', type: 'bytes' }],
		outputs: [],
		stateMutability: 'nonpayable',
	},
	{
		type: 'function',
		name: 'claim',
		inputs: [],
		outputs: [],
		stateMutability: 'nonpayable',
	},
	{
		type: 'function',
		name: 'claimed',
		inputs: [{ name: '', type: 'address' }],
		outputs: [{ name: '', type: 'bool' }],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'deadline',
		inputs: [],
		outputs: [{ name: '', type: 'uint256' }],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'expire',
		inputs: [],
		outputs: [],
		stateMutability: 'nonpayable',
	},
	{
		type: 'function',
		name: 'feeBps',
		inputs: [],
		outputs: [{ name: '', type: 'uint256' }],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'feeRecipient',
		inputs: [],
		outputs: [{ name: '', type: 'address' }],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'feeWithdrawn',
		inputs: [],
		outputs: [{ name: '', type: 'bool' }],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'getClaimable',
		inputs: [{ name: 'user', type: 'address' }],
		outputs: [{ name: '', type: 'uint256' }],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'gracePeriod',
		inputs: [],
		outputs: [{ name: '', type: 'uint256' }],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'outcomeCount',
		inputs: [],
		outputs: [{ name: '', type: 'uint256' }],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'question',
		inputs: [],
		outputs: [{ name: '', type: 'string' }],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'resolve',
		inputs: [
			{ name: '_winningOutcome', type: 'uint256' },
			{ name: 'signature', type: 'bytes' },
		],
		outputs: [],
		stateMutability: 'nonpayable',
	},
	{
		type: 'function',
		name: 'signer',
		inputs: [],
		outputs: [{ name: '', type: 'address' }],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'status',
		inputs: [],
		outputs: [{ name: '', type: 'uint8' }],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'totalPerOutcome',
		inputs: [{ name: '', type: 'uint256' }],
		outputs: [{ name: '', type: 'uint256' }],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'totalPool',
		inputs: [],
		outputs: [{ name: '', type: 'uint256' }],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'userBets',
		inputs: [
			{ name: '', type: 'address' },
			{ name: '', type: 'uint256' },
		],
		outputs: [{ name: '', type: 'uint256' }],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'winningOutcome',
		inputs: [],
		outputs: [{ name: '', type: 'uint256' }],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'withdrawFee',
		inputs: [],
		outputs: [],
		stateMutability: 'nonpayable',
	},
	{
		type: 'event',
		name: 'BetPlaced',
		inputs: [
			{ name: 'user', type: 'address', indexed: true },
			{ name: 'outcomeIndex', type: 'uint256', indexed: true },
			{ name: 'amount', type: 'uint256', indexed: false },
		],
	},
	{
		type: 'event',
		name: 'Claimed',
		inputs: [
			{ name: 'user', type: 'address', indexed: true },
			{ name: 'payout', type: 'uint256', indexed: false },
		],
	},
	{
		type: 'event',
		name: 'FeeWithdrawn',
		inputs: [{ name: 'amount', type: 'uint256', indexed: false }],
	},
	{ type: 'event', name: 'MarketCancelled', inputs: [] },
	{ type: 'event', name: 'MarketExpired', inputs: [] },
	{
		type: 'event',
		name: 'MarketResolved',
		inputs: [{ name: 'winningOutcome', type: 'uint256', indexed: true }],
	},
] as const
